# Generated by Django 2.0.2 on 2018-02-18 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_test', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='answer_true',
            field=models.IntegerField(default=1, verbose_name='Правильный ответ'),
        ),
    ]
